[workspace]
resolver = "2"
members = [
    "contracts/cashier",
    "contracts/chips",
    "contracts/lobby",
    "contracts/signal",
    "contracts/test_usdc",
    "contracts/verify_shuffle",
    "contracts/verify_unmasking",
    "common"
]

[workspace.dependencies]
alloy-primitives = "=0.8.20"
alloy-sol-types = "=0.8.20"
bls12_381 = { version = "0.8.0", features = ["experimental"] }
dotenv = "0.15.0"
digest = "0.9.0"
ethers = "2.0"
eyre = "0.6.8"
ff = "0.13.1"
hex = { version = "0.4", default-features = false }
pairing = "0.23.0"
privatepoker-common = { path = "./common" }
stylus-sdk = "0.9.0"
tokio = { version = "1.12.0", features = ["full"] }

[profile.release]
codegen-units = 1
panic = "abort"
opt-level = "z"
strip = true
lto = true
debug = false
rpath = false
debug-assertions = false
incremental = false

[profile.dev]
panic = "abort"
