[package]
name = "signatory"
version = "0.1.11"
edition = "2021"
description = "Private Poker Signatory"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
privatepoker-common = { workspace = true }
stylus-sdk = { workspace = true }

[dev-dependencies]
stylus-sdk = { workspace = true, features = ["stylus-test"] }

[features]
default = ["mini-alloc"]
export-abi = ["stylus-sdk/export-abi", "privatepoker-common/export-abi"]
test-debug = [
    "privatepoker-common/test",
    "privatepoker-common/debug",
    "stylus-sdk/debug",
]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "signatory"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]
