[package]
name = "verify_signature"
version = "0.1.11"
edition = "2021"
description = "Private Poker Verify Signature"

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
bls12_381 = { workspace = true }
digest = { workspace = true }
hex = { workspace = true }
pairing = { workspace = true }
stylus-sdk = { workspace = true }
# stylus-core = { workspace = true }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["sha3-keccak"] }
stylus-sdk = { workspace = true, features = ["stylus-test"] }
tokio = { workspace = true, features = ["full"] }
eyre = { workspace = true }
dotenv = { workspace = true }

[features]
default = ["mini-alloc"]
export-abi = ["stylus-sdk/export-abi"]
test-debug = [
    "stylus-sdk/debug",
]
mini-alloc = ["stylus-sdk/mini-alloc"]

[[bin]]
name = "verify_signature"
path = "src/main.rs"

[lib]
crate-type = ["lib", "cdylib"]
